### ISSUE TITLE
Running /reminders with no arguments produces an internal error

### ISSUE THREAD

**Issue by The-Fireplace** [c10coding/Reminders#1]
Expected behavior:
Some kind of overview shows up with all the subcommands, maybe plugin version as well.
Actual behavior:
Internal error occurs - https://paste.ubuntu.com/p/CQFxfBSHp6/
PlugMan v2.1.7
Reminders v2.0

**Comment by its-c10** [comment]
> Expected behavior:
> Some kind of overview shows up with all the subcommands, maybe plugin version as well.
> Actual behavior:
> Internal error occurs - https://paste.ubuntu.com/p/CQFxfBSHp6/
> PlugMan v2.1.7
> Reminders v2.0

I didn't know anyone actually used this plugin haha. Glad to know someone's using it. I'll update it tomorrow 👍

**Comment by The-Fireplace** [comment]
I've only just started using it, I just started my server.

**Comment by its-c10** [comment]
Fixed via Remindersv3.0.0: https://www.spigotmc.org/resources/reminders.71905/
